### ISSUE TITLE
Can you provide information on whether results are cached?

### ISSUE THREAD

**Issue by SimonEast** [hut6/oembed#1]
Great plugin. We're looking at using this for an upcoming project. Couldn't see any info in your readme (or that of the Essence library) that relates to caching. I assume that the library has to make remote HTTP requests to fetch some of the info to render the embeds, is that right? If so, then that's gonna slow down page rendering unless the results are cached.

Any info you might be able to provide about that would be great. And perhaps it would go well in the readme too. 🙂

**Comment by SimonEast** [comment]
Oh, after looking more at the two ways to render the embed code...

```
{{ entry.mediaUrl.embed }}
{{ craft.oembed.embed(url, options) }}
```

I assume the first method generates the embed code *when the entry is saved* - is that right? While the second method does it on rendering. So the first would perform much faster - is that right?

**Comment by reganlawton** [comment]
@SimonEast Sorry for the late update. The codes are rendered using TemplateHelper::getRaw() method and then used in a template which has the {% cache %} tag should cache fine. We haven't come into performance issues so far most of are site use the {% cache %} tag heavily.
