### ISSUE TITLE
Template tags not working

### ISSUE THREAD

**Issue by eablokker** [hut6/oembed#10]
My field handle is named `oembed`.

`{{ entry.oembed }}` gives me the plain text url that I entered into the field.

`{{ entry.oembed.embed }}`
Impossible to access an attribute ("embed") on a null variable.

`{{ craft.oembed.embed(entry.oembed) }}`
Neither the property "embed" nor one of the methods "embed()", "getembed()"/"isembed()"/"hasembed()" or "__call()" exist and have public access in class "hut6\oembed\variables\OembedVariable".

`{{ entry.oembed.media.title }}`
Impossible to access an attribute ("media") on a null variable.

Not sure if I'm using that last tag correctly.

PHP 7.2.1
Craft Pro 3.0.2
oEmbed 2.0.7

**Comment by reganlawton** [comment]
Ok @eablokker upgrade to v2.0.8 and the README has been updated there were alot of changes going from CraftCMS 2.5 to 3.0 few things were still needing updating

**Comment by eablokker** [comment]
Ok, also I think I was making an error on my side. I was looping through multiple entry types, some of which don't have the oEmbed field on them. So when I tried to call the embed method on it, the types which don't have the field would error. I needed to add a conditional to check if it was a certain entry type before rendering the oEmbed.

I'm seeing it working now! Yess! Thanks!
