### ISSUE TITLE
“Could not find any embeddable media from this URL.” for some services on *.localhost

### ISSUE THREAD

**Issue by klick** [hut6/oembed#7]
I get a “Could not find any embeddable media from this URL.” error message when using a twitter status url. I assume the problem is a cross-domain violation of some sort? Or the twitter embed api doesn’t allow non-generic tlds?

Anything we could do?
The craft logs don’t reveal much else too.

**Comment by ryancastle** [comment]
Can the server definitely resolve those URLs? It's just a regular curl request on the server.

**Comment by klick** [comment]
Craft runs on local apache, macOS 10.11. Other oembed Plugins are throwing errors too. Only twitter though. Wird.

**Comment by reganlawton** [comment]
@klick whats the url your trying to use?

**Comment by klick** [comment]
@reganlawton The twitter URL? That’s the standard on. I.e. : https://twitter.com/Interior/status/463440424141459456

**Comment by klick** [comment]
Can I configure curl options somewhere? Might be an SSL thing.

**Comment by reganlawton** [comment]
@klick oEmbed interfaces `essence/essence` so you can't manage the `verify_peer` CURL option that you'd most likely need here.

**Comment by reganlawton** [comment]
Closing due to issue being related to `essence/essence` sub package.
