### ISSUE TITLE
Method hut6\oembed\models\OembedModel::__toString() must return a string value

### ISSUE THREAD

**Issue by eablokker** [hut6/oembed#8]
PHP Recoverable Error – yii\base\ErrorException
Method hut6\oembed\models\OembedModel::__toString() must return a string value

vendor/hut6/oembed/src/fields/OembedField.php at line 113
```
public function getInputHtml($value, ElementInterface $element = null): string
{
    return '<input name="'.$this->handle.'" value="'.$value.'" />';
}
```

PHP 7.2.1
Craft Pro 3.0.2
oEmbed 2.0.0

**Comment by reganlawton** [comment]
@eablokker any additional information? What was your twig code if available

**Comment by eablokker** [comment]
Ah, I forgot to explain how to reproduce. There is no twig code. This is simply adding an oEmbed field, then adding that field to an entry type. When you go to edit an existing entry which has the new field, this error shows up. If you try to create a new entry with the field, you get a small notification that says an unknown error occurred. When I remove the oEmbed field from the entry type, then I can edit those entries again.

**Comment by reganlawton** [comment]
@eablokker Thanks for the additional I'll try get you a fix today

**Comment by reganlawton** [comment]
@eablokker can you update your oEmbed version to `2.0.4`

**Comment by reganlawton** [comment]
@eablokker 

Ok you should now be able to run `composer update hut6/oembed` and/ or use `"hut6/oembed": "2.0.*",`. 

That will give you the latest updates, which I've tested as working.

**Comment by eablokker** [comment]
Ok thank you, that fixed the issue. I was able to add a field to an entry type and enter a url into the field and save. However the twig tags in the template don't seem to be working. I'll create another ticket.
